### ISSUE TITLE
White screen after few seconds on board

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1086]
After a few seconds the screen turns white and is not available until a refresh

<img width="840" alt="Screenshot 2021-11-23 at 09 32 43" src="https://user-images.githubusercontent.com/1539948/142992050-81cff028-a546-4938-b3a4-dbe4f7c875a2.png">

**Comment by Dominik-Weinzierl** [comment]
Interesting - seems like this works in Firefox, but not in Chrome 🤔
