### ISSUE TITLE
Missing button design for error page

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [inovex/scrumlr.io#1108]
## Description
![Screenshot 2021-11-29 at 09 58 58](https://user-images.githubusercontent.com/60005702/143838158-2cf781ab-901f-450c-822d-620451c496f8.png)

**Comment by bitionaire** [comment]
I added a new `<Button />` component with the merge of the landing page branch. I guess we can start implementing it on the previous screens. I already opened a ticket for the `<PasswordDialog />`. Should we reuse this issuefor the error page?

**Comment by Dominik-Weinzierl** [comment]
Yes sounds good. I think we can close this :)
