### ISSUE TITLE
Implement participants list redesign

### ISSUE THREAD

**Issue by dbaderINO** [inovex/scrumlr.io#1247]
As a user I want to see a brief list of participants which includes ...

- the avatars
- the display names of the users
- their role (owner/creator, moderator)
- their ready state

I want to paginate through the list if many users have joined the board. Then I want to also filter the list of users by the display name.

An extended view should include online & offline users while the brief overview should only include online users.

As a moderator I want to add and revoke other moderators.

**Comment by bitionaire** [comment]
I guess the current state of the participants view within the board settings should be enhanced by 

- options to filter by online/offline state
- counter of "ready" users (only considering online participants)
- a search input for user names

also it should be sorted by the participant roles (owner first > moderators second > participants), the online state and the usernames.


Also I want to know whether we should open the participant view within the board settings on click of the user avatars on a board or keep the dropdown?

**Comment by bitionaire** [comment]
New AC:

The current state of the participants view within the board settings should be enhanced by

- options to filter by online/offline state
- counter of "ready" users (only considering online participants)
- a search input for user names

also it should be sorted by the participant roles (owner first > moderators second > participants), the online state and the usernames.

**Comment by Kraft-16** [comment]
filter function: https://xd.adobe.com/view/274044ba-edff-4c4f-b63f-08f7e5325e62-7213/
offline user: https://xd.adobe.com/view/2c1b6f6b-9473-46f4-8194-5b4a44232b3a-7948/
change role (moderator/participant): https://xd.adobe.com/view/7f3e8a0a-82e2-4744-80cf-f7049bd381fe-2a6d/
reset ready states: https://xd.adobe.com/view/31dc12cb-4503-47eb-8ffd-1d5f5a5147b9-648f/
