### ISSUE TITLE
Design focus mode

### ISSUE THREAD

**Issue by dbaderINO** [inovex/scrumlr.io#1249]
As a moderator of board I want to highlight notes for all users with a focus mode ...

- If the focus mode is active all detail views of the notes will be shared with other users
- Activated Focus mode guides the user to click on cards, in order to share it with other participants 
- Consider: I want to navigate trough the notes by several sorting options. Previous and next notes should be displayed and I should be able to navigate through the list with the arrow keys on the keyboard
  - By columns
  - By the vote results
  - By users

**Comment by bitionaire** [comment]
Part of #1817
