### ISSUE TITLE
Implement new design of actions bars

### ISSUE THREAD

**Issue by dbaderINO** [inovex/scrumlr.io#1251]
**As a user I want to see a action bar in order to ...**

- mark myself as ready
- add a reaction
  - laugh
  - heart
  - thumbsup
  - thumbsdown
  - raise hand
- access the user settings
- ... ?

**As a moderator I want to see a action bar in order to ...**

- access the column edit mode
- start or stop a timer
- start or stop a voting session
- start the focus mode
- consider another option to reset active states (e.g. timer, ready state of users, vote ...)

**Comment by bitionaire** [comment]
My suggestion:

- Keep action as is and add missing functions later on
- Keep action bars left/right on larger screens (e.g. tablet), no matter how many columns a board has
- Move scroll button positions on larger screens (e.g. below actions bars, in the bottom corners or at the bottom center)
- Disable tooltips for action bar on mobile screens or enable them by long press (#1722)
- Choose whatever looks and feels best for mobile screens (e.g. toggle between user/admin bar or layout the bars vertically and horizontally)

**Comment by bitionaire** [comment]
Update by design:

- Keep current list of actions for now
- Move scroll left/right buttons to action bars as suggested in the design (and hide them on mobile screens)
- Change colors as suggested in the design
- Change action bar to fav button (burger menu) on mobile which opens the actions vertically (admins) and horizontally (regular participants)
- Hide labels on mobile screens and just keep the icons

@Kraft16 can you share a link to the design concept here?

**Comment by timengel** [comment]
I think a slightly darker color on disabled arrows would improve the visibility. On my screen, the disabled arrows were barely visible and that was confusing.

| Enabled        | Disabled (old)           | Disabled (suggestion)  |
| ------------- |:-------------:| -----:|
| ![image](https://user-images.githubusercontent.com/32651718/180199196-373d91e7-c1e8-48e1-b17c-b538c872bf3b.png) | ![image](https://user-images.githubusercontent.com/32651718/180198211-1238796d-48f7-4c16-b814-d191401b8643.png) | ![image](https://user-images.githubusercontent.com/32651718/180200597-5e8a3812-93db-4856-bb65-723c4a9bb4d4.png) |

**Comment by Kraft-16** [comment]
Action Bar for Mobile devices
https://xd.adobe.com/view/6e4e8128-3c24-4e24-8409-56c192e0b25b-3b1d/
