### ISSUE TITLE
Legal Documents

### ISSUE THREAD

**Issue by dbaderINO** [inovex/scrumlr.io#1253]
As a user I want to quickly open & scan all legal documents including ...

- the terms & conditions
- the privacy policy
- the cookie policy

**Comment by Kraft-16** [comment]
a new design: https://xd.adobe.com/view/939e12fd-7e8f-401c-a546-ae8a4963f654-c6cd/

- The distance between the title text and the main test should be about 30 px.

![Image](https://user-images.githubusercontent.com/84507845/208308790-69b85685-5c12-40b6-b600-6de538eb25ae.png)

- The enumeration list should start with a bullet (as in the current version).

![Image](https://user-images.githubusercontent.com/84507845/208308807-8a1074c7-a881-4c4b-953a-32da76eb923e.png)

**Comment by Kraft16** [comment]
A new design of legal documents:

Light mode_en for desktop 
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1423%3A28441&type=design&node-id=1423-45299&viewport=-918%2C537%2C0.07&scaling=min-zoom&starting-point-node-id=1423%3A45299

Light mode_en for mobile devices
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1423%3A28441&type=design&node-id=1495-34120&viewport=-3877%2C604%2C0.17&scaling=min-zoom&starting-point-node-id=1495%3A34120

Dark mode_en for desktop
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1423%3A28441&type=design&node-id=1429-52662&viewport=-23891%2C1538%2C0.66&scaling=min-zoom&starting-point-node-id=1429%3A52662

Dark mode_en for mobile devices
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1423%3A28441&type=design&node-id=1664-34048&viewport=-23891%2C1538%2C0.66&scaling=min-zoom&starting-point-node-id=1664%3A34048

**Comment by Resaki1** [comment]
This is labeled `Landingpage` - should the landingpage really have its own legal documents or just link to the ones already existing on scurmlr.io? @bitionaire

**Comment by bitionaire** [comment]
> This is labeled `Landingpage` - should the landingpage really have its own legal documents or just link to the ones already existing on scurmlr.io? @bitionaire

Just do it :)
