### ISSUE TITLE
Design board mode template gallery

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1261]
**As a board creator I want to select a template from several board modes ...**

- I want to select a template from a list of curated modes
- I want to select a template from a list of user created templates
  - I want to search the templates by the name
  - I want to sort the templates by the number of usages
  - Consider to add an option to rate the user created templates and sort them
  - Consider to add an option to sort the templates by latest usage
- Consider also that a user might want 
  - ... to see his own created templates
  - ... his latest used templates 

**As a board creator I want to create my own board modes from the template gallery ...**

- A template name should be defined
- The columns must be defined
- The default visibility of the columns must be defined
- Consider that a user might manually choose the column colors or let them be defined by a fixed order

**As a board user I want to export my current column setup into a template**

- A template name must be set

**Comment by SelinaBuff** [comment]
Just the illustrations have to be create
