### ISSUE TITLE
Admin can lockout himself

### ISSUE THREAD

**Issue by Doogiemuc** [inovex/scrumlr.io#131]
I create a **private** board. (With the default simple retro layout.)
I was the admin and other members were able to join.
Then I pressed reload in my browser (F5)  

As a consequence, I was logged out of my own board and couldn't "login" as admin again.  When I clicked on the join link again, I would have been able to join the board as a new user. But then I was stuck at "Waiting for the admin to grant you access".

Expected behaviour:
There should be a way for the admin to re-login to a private board. Some other tools provide a special "admin link" for this.

**Comment by bitionaire** [comment]
I'll close this issue since i can't reproduce it and we will release a new version of scrumlr hopefully this year.
