### ISSUE TITLE
Option for not displaying newly added cards immediately

### ISSUE THREAD

**Issue by michaelamaura** [inovex/scrumlr.io#133]
We as a team like a short brainstorming phase at the start of the meeting where we are not influenced by the others.

So it would be great being able to start with the cards "turned around", i.e. with the content not visible. Then, after some time, the cards could be "turned around" and then consolidation and discussion could start.

This could be handled as an (optional) seperate phase, like Phase 0: "brainstorm"

**Comment by bitionaire** [comment]
HI @michaelamaura, we did consider this option for our release of a new tool version in https://github.com/inovex/scrumlr.io/projects/3
