### ISSUE TITLE
Order cards by user for presenting them

### ISSUE THREAD

**Issue by bb-dsa** [inovex/scrumlr.io#137]
In a retrospective everyone has to present his cards and explain them. Thus it would be helpfull to order the cards or filter them by user. Maybe a new phase "Explain" would make sense.

User story:
As a participant I'd like to step through all my cards to explain them to other ordered from the first to last column. 
As a participant I'd like to see a timer of how much time is left for presenting my cards.

**Comment by bitionaire** [comment]
Hey @bb-dsa, we will hopefully release a new version of scrumlr this year and improved the usability & flexibily, so hopefully you will be satisfied with the new experience soon :)
