### ISSUE TITLE
Export creates only 1 page PDF

### ISSUE THREAD

**Issue by Aelindara** [inovex/scrumlr.io#138]
When you try to export a board (in my case "Simple Retro") you get send to the print view (you see all list, cards etc.), but when you try to print it as pdf only the first page is shown in the print preview window and not the whole board. The resulting PDF also has only one page.

**To Reproduce**
1. Klick "Export" in scrumlr.io
2. Print window with preview opens
3. Klick "Print"
4. Select folder
5. PDFs is created
6. PDF only has 1 page

**Expected behavior**
PDF with all lists and cards (whole board, longer then one page)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Version 76.0.1 (64-Bit)

PS: Great tool! THX!

**Comment by bitionaire** [comment]
Hey @Aelindara, we basically stopped our efforts to improve the current online version of scrumlr ago but I guess that bug should be already fixed? Anyway, we will hopefully release a new version of scrumlr this year without a bug in the PDF export :)
