### ISSUE TITLE
Moving cards across lanes

### ISSUE THREAD

**Issue by Heimschmiede** [inovex/scrumlr.io#139]
Feature Reqeust:

It would be nice being able to move cards across lanes.
E.g.: When doing a Mad/Sad/Glad session and while grouping the bad cards together then I cannot group cards from mad and sad together.
This assumes I can move cards as well between lanes. Sometimes a card got wrongly assigned to a lane (e.g. Mad)

**Comment by bitionaire** [comment]
Hi @Heimschmiede , we will add this feature in a new scrumlr version which we'll hopefully release this year.
