### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by monizb** [inovex/scrumlr.io#140]
How to run this project locally? Please define the steps in the README.md file, thank you

**Comment by theexiile1305** [comment]
@monizb Thank you for the question. Please feel free to add any pull request to the project, but for sure I wanna add a little description into the README. 
Currently I want to give you some instruction how to start the application locally:

Please note the following side notes:
- The current productive and hosted application is on [Branch v1](https://github.com/scrumlr/scrumlr.io/tree/v1)
- The project is basically a Firebase-project and therefore you have to setup yourself a project within the [Firebase Console](https://firebase.google.com/)
- The database rules are manifested in  `database.rules.json`
- The firebase config is located in `src/config.ts` as a simple object that can be exported from your firebase project.

1. You have to install npm stuff like node, npm, yarn. etc. becuase this project is a basic npm project. 
2. Install all dependencies via `npm install` or `yarn install`
3. Start the app via `npm start` or `yarn start`

I hope that I could answer all the questions.  If not, then I can support you further.

**Comment by monizb** [comment]
Hey @theexiile1305 ,
Thanks for the quick response. I have done all the steps as told by you.Although while running using `npm start` I get the following error during build:

`/Users/monish/Downloads/scrumlr-1.io-1/node_modules/@types/react/index.d.ts
ERROR in /Users/monish/Downloads/scrumlr-1.io-1/node_modules/@types/react/index.d.ts(2664,19):
TS2320: Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any, any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any, any>' are not identical.`

The `npm install` worked with no issues, but still I do not know if I'm doing something wrong here, also I did try to search around for this error but didnt find anything useful, hopefully you can help me out as I really would like to contribute to this project.

**Comment by theexiile1305** [comment]
Hey @monizb,
sorry for the late response. Can you please give me the informations about your node and npm version, because whenever I checkout the repo and run it no error occurs.

**Comment by monizb** [comment]
Hey @theexiile1305,
Here are the versions:
node: 12.18.1
npm: 6.14.5
On trying to search online I found that @types had a weird hardcoded react version which was not compatible with my current version, not sure how to fix it though.

**Comment by theexiile1305** [comment]
Hey @monizb 
I just checked the repository with the branch `v1` out and run `npm install && npm start`. In this situation I got no error. 
Can you provide me the full stacktrace of the failure?

**Comment by monizb** [comment]
@theexiile1305 Actually , that's the only error I receive while running, could you please tell me your npm and node versions so that I can maybe downgrade to those versions and check if that resolves the error? Thank you.

**Comment by theexiile1305** [comment]
Hey @monizb, 
my current npm version is `6.14.5` and node version is `v14.0.0`

**Comment by bitionaire** [comment]
Hey, we'll release a new version of scrumlr hopefully this year and I think we already improved the quality of our README.md. By the time we'll be able to release I think everything will be well documented, since we started to work as a team and need this for ourselves too :)
