### ISSUE TITLE
X-Scrolling does not work on Safari 15.4

### ISSUE THREAD

**Issue by Dakicka** [inovex/scrumlr.io#1580]
Hi,
I could have sworn I already saw a bug ticket for this but I can't find it anymore. 
The scroll buttons did not work on my safari browser (15.4).

I would like to contribute a fix but I am not exactly sure how since it is my first open source contribution.
Just open up a new PR and referencing this issue?

**Comment by bitionaire** [comment]
Hey @Dakicka, I just merged your PR and wanted to thank you for your contribution!
