### ISSUE TITLE
Update/Upgrade dependencies

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1625]
* Update/Upgrade all frontend dependencies, so that the project is compatible with the latest versions of node.js, TypeScript etc.

**Comment by timengel** [comment]
Update `react-scripts` Error: Das neueste `react-script 5.0.1` bzw. dessen dependency `svgr` wirft Fehler beim rendern von SVGs die `CDATA` Blocks beinhalten. Der [Bug](https://github.com/facebook/react/issues/22518) ist bekannt und wurde anscheinend in `svgr 6.x` [gefixt](https://github.com/gregberge/svgr/issues/558).  
  
Leider unterstützt `react-script 5.0.1` maximal `svgr 5.x`. Deshalb ist die einzige Möglichkeit den Fehler zu Umgehen die`CDATA` Blocks aus den SVGs zu entfernen. Das sollte auch funktionieren (siehe [hier](https://www.ibm.com/docs/en/txseries/8.1.0?topic=reference-working-cdata-section)), aber ich denke da müssten sich die Designer drum kümmern. Alternativ kann man auch warten bis `svgr 6.x` unterstützt wird.
