### ISSUE TITLE
Setting default board settings

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1626]
As the default board configuration hidden columns should be visible for all moderators. At the moment they are hidden, which might raise questions for the users.

Also we should check, whether we invert the labels for the hide author name settings.

<img width="382" alt="Screenshot 2022-05-03 at 08 51 35" src="https://user-images.githubusercontent.com/1539948/166422584-43b862a0-e4d5-42ae-82f8-01a3fd10256f.png">

**Comment by brandstetterm** [comment]
I think it would be best if the labels remain the same for both toggle states. For example 
- Hide authors of cards [Yes/No]
- Hide notes of other users [Yes/No]
- Show hidden columns [Yes/No]
