### ISSUE TITLE
Align column context menu button with input field

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1632]
Align the column context icon with the "add" icon within the input field for new notes. 

<img width="494" alt="Screenshot 2022-05-03 at 12 38 04" src="https://user-images.githubusercontent.com/1539948/166439610-023acb56-d2cc-4b4d-9345-c50242b5e00f.png">

**Comment by timengel** [comment]
Wo ich gerade schon dabei bin Dinge zu alignen, soll ich das mit den headers auch machen?
![image](https://user-images.githubusercontent.com/32651718/166473804-afa92831-1dd8-4d35-bde5-ba9dcbfd9f44.png)
⬇️
![image](https://user-images.githubusercontent.com/32651718/166473935-2c18c74f-e13a-4473-86b4-bfb61a3dd316.png)
