### ISSUE TITLE
Fix: backdrop-filter not supported in Firefox

### ISSUE THREAD

**Issue by timengel** [inovex/scrumlr.io#1646]
The [backdrop-filter](https://developer.mozilla.org/de/docs/Web/CSS/backdrop-filter) property which is used to blur the background of note dialogues is not supported in Firefox.  

ToDo:
- [ ] Implement a workaround, e.g. as in [Glassmorphism for Firefox](https://medium.com/web-dev-survey-from-kyoto/glassmorphism-for-firefox-2113dff03747) or SVG filters

Firefox:
![image](https://user-images.githubusercontent.com/32651718/167167790-af407f02-9db8-43d2-9027-58d7a64335b2.png) 
 
Chrome:
![image](https://user-images.githubusercontent.com/32651718/167167921-73db7c2e-2c94-4fac-970c-e7f764acd7f7.png)

**Comment by Resaki1** [comment]
They are working on bringing backdrop-filter back to Firefox though, and it should be available "soon". Maybe not worth the effort to implement a workaround, as it is not really critical for us?

**Comment by brandstetterm** [comment]
Maybe it's worth mentioning that backdrop-filter does work on Firefox but you must explicitly enable the feature.

**Comment by timengel** [comment]
Yes, I think we can put this in the "spare time" section ;)
