### ISSUE TITLE
Reorder notes within stack view

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1657]
As a moderator I want to reorder notes within the stack view by drag & drop.

On drag & drop lines should be displayed between the notes to highlight the different locations where I can drop my note into (either on hover or displayed statically). 

Once I hover over a line the line should change it's color or size.

We should experiment with animations here and choose what's best.

**Comment by Kraft-16** [comment]
design option: https://xd.adobe.com/view/9a9600fc-a7e6-4df9-b803-dc47f0bbb31a-cfc5/
- A dashed outline is displayed on the empty place of the dragged card.
- The appearance of the outline on the card indicates the selected place to move.
