### ISSUE TITLE
Reorder notes within board view

### ISSUE THREAD

**Issue by timengel** [inovex/scrumlr.io#1700]
As a moderator I want to reorder notes within the board view by drag & drop.

- [ ] On drag & drop, an indicator should appear at the current drop position (e.g. note-sized placeholder)

We should experiment with animations here and choose what's best.

[JUST LIKE THIS EXAMPLE!](https://github.com/clauderic/dnd-kit/issues/127#issuecomment-1006671833)

**Comment by CronJorian** [comment]
@Kraft16 is this design still up-to-date? :)

**Comment by Kraft-16** [comment]
@CronJorian no, this design is not relevant.

**Comment by brandstetterm** [comment]
I think this ticket is blocked until #1859 has been completed. We first have to research and decide which sorting method fits our needs best.
