### ISSUE TITLE
Change icon color for JSON export

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1721]
Icon is hard to see

![image](https://user-images.githubusercontent.com/1539948/169691016-3ce97176-6ee5-4226-bfba-cd7c90c73db9.png)

**Comment by Resaki1** [comment]
![Bildschirmfoto 2022-05-24 um 13 34 06](https://user-images.githubusercontent.com/35272402/170025323-45100993-7fe6-4d53-83b5-fe729e2bdb85.png)
Maybe like this? File stroke opacity of 1 and Text color white and opacity 0.75
