### ISSUE TITLE
Change number of touches for action bar

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1722]
While a button is focused/active in the action bar only one tap should be necessary to toggle it. Currently one need two taps to disable eg the ready state though it seems active

- change to long-press to show tooltip, single press to activate action

![image](https://user-images.githubusercontent.com/1539948/169691075-8422716c-9836-4bc6-8f72-4607cdfd1d19.png)

**Comment by brandstetterm** [comment]
Remove tooltips for mobile for now (but think about a setting where you can reactive them)

**Comment by Resaki1** [comment]
closed as tooltips won't be shown on mobile anymore
