### ISSUE TITLE
Column header should not scroll on mobile

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1725]
![image](https://user-images.githubusercontent.com/1539948/169691362-8bd00a21-1630-41c7-b107-03512c14da74.png)

**Comment by brandstetterm** [comment]
https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/

**Comment by Resaki1** [comment]
It's possible to scroll the column through the note stack view

**Comment by CronJorian** [comment]
> It's possible to scroll the column through the note stack view

Couldn't reproduce the scrolling on android browser, safari, firefox or chrome...

**Comment by CronJorian** [comment]
Is a iOS specific bug
The scrolling on android is fixed
