### ISSUE TITLE
Change timer sounds

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#1735]
Last 3 seconds: TIK - TOK - TIK - BOOM!

Reduce volume to 50%

**Comment by timengel** [comment]
Known bugs:
- Hardware media keys occasionally affect timer audio (e.g. play/pause, audio flickering, etc.)
- Page reload after timer ended occasionally restarts countdown audio and timer end audio
- Timer audio playback "locks" hardware media keys, preventing other Apps from responding to them (e.g. Spotify)
