### ISSUE TITLE
Line breaks in note text are not saved

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#1736]
Also, the text element is <blockquote /> which seems wrong?

**Comment by brandstetterm** [comment]
I don't know if that's wrong behavior, to be honest.
Our inputs don't allow to line break since hitting enter adds the note. So the only possible way to have line breaks right now is to edit a note.

**Comment by timengel** [comment]
In many cases where "Enter" submits an input you can use "Shift" + "Enter" to add a line break instead.

**Comment by bitionaire** [comment]
I vote for disabled line breaks while editing

**Comment by brandstetterm** [comment]
AC:
- Disable line breaks in the text area in the details screen
