### ISSUE TITLE
Hotkey concept

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#1738]
I'd be great if users could use scrumlr only using hotkeys. Collect ideas for possible hotkeys.

User tests could be helpful to check if simple hotkeys (like pressing "R" to mark as ready) are often activated on accident and more complex hotkeys (like pressing "STRG + R") are necessary

**Comment by Resaki1** [comment]
Some ideas:

- "R" -> ready/unready
- "H" -> raise/lower hand
- "S" -> settings
- "T" -> toggle timer menu (we need focus states on the timer options!)
- "V" -> toggle voting menu
- "F" -> toggle focus mode
- "P" -> toggle participants list
- "1"-"9" -> open input field of column 1 to 9

**Comment by timengel** [comment]
I suggest that we add an "Enable Hotkeys" option to the Header Menu for all users.
