### ISSUE TITLE
Frontend docker image does not work on OpenShift

### ISSUE THREAD

**Issue by seschi98** [inovex/scrumlr.io#1741]
Hi, this is a follow-up issue for #1697.

As I discussed with @bitionaire via email, some environments require the execution of containers as non-root user. In the mentioned PR the frontend docker image was changed to use the `nginx-unprivileged` base image.

Unfortunately I get the following error when running the image in Red Hat OpenShift:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/scrumlr.io.conf.template to /etc/nginx/conf.d/scrumlr.io.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/05/25 09:21:58 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

This is because in the `nginx.conf` the port is set to `80`, which does not work for non-root users.

Possible solutions:
1. Use an environment variable for the nginx port so users can override the value if they have the same problem (but default it to 80)
1. Change the port in the config (for example `8080`) which would be a breaking change but reduce the need to re-configure it

Also, I do not think that the routing problem was fixed in #1697, because when I access the `/login` URL I still get a nginx 404 page (maybe because the nginx.conf needs to be set as the default.conf and not an additional scrumlr.io.conf?)

**Comment by bitionaire** [comment]
Hello! @brandstetterm can you have a look into this issue? You can pass env variables to the ngigx.conf template and just need to replace the :80 port in the listen attribute. I think you can set a default value in the dockerfile ENV. It should stay at 80 as the default setting :)
Thank you!

**Comment by bitionaire** [comment]
I just added the env `SCRUMLR_LISTEN_PORT` which you can set to `8080` in order to fix the issue. The route `/login` was unavailable due to a bug in the frontend or at least that's what I found in my local test. Can you check the new image and whether it resolves your issues @seschi98? If everything works fine I'll create a new release.

```
docker pull ghcr.io/inovex/scrumlr.io/scrumlr-frontend:sha-8e39d56
```

**Comment by seschi98** [comment]
@bitionaire The routing is still not working. You can check out https://scrumlr-seschi98-stage.apps.sandbox.x8i5.p1.openshiftapps.com/ to test it yourself...

**Comment by bitionaire** [comment]
Ok @seschi98 should be fixed now. I added the flag `default_server` in the conf template and also set `server_name _` so that this conf will be used for all requests regardless of the host. Now it works on all hosts and not only on `localhost`. Please try following image:

```
docker pull ghcr.io/inovex/scrumlr.io/scrumlr-frontend:sha-a6e2939
```

**Comment by seschi98** [comment]
Hey @bitionaire, 
it seems to work now :+1: Thanks a lot!
