### ISSUE TITLE
Missing focus states

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#1749]
Many buttons don't have proper focus states, which makes it hard to navigate using the tab key. Examples are the menu items, the buttons in timer and voting menu, and the settings dialog

**Comment by Resaki1** [comment]
wait for #1901 to be merged to avoid design inconsistencies and merge conflicts

**Comment by bitionaire** [comment]
Is this fixed with #1901 @Resaki1?

**Comment by Resaki1** [comment]
@bitionaire no, the focus (no pun intended) in #1901 was only on hover states. There are still many interactive elements without focus states or only the default browser implementation
