### ISSUE TITLE
Emojis on board to display own reactions

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#177]

**Comment by SelinaBuff** [comment]
Reactions will show when i hover over the card (under – like a lappen). We should do it like GitHub and the emojis will be shown on the notes (as much as possible). Emojis: heart, thumb up, thumb down, clapping hands or celebration, sceptical smiley, laughing/happy smile and suprised smiley. Eveyone can react on the same Reaction and we will show the usernames in a tooltip (max: 12).

**Comment by SelinaBuff** [comment]
#2800

**Comment by SelinaBuff** [comment]
Almost done (see Figma file - at **components**: _Reactions_). Darkmode is done so far, i just have to transfer it in lightmode (will be created from 10.7 - 12.7).

**Comment by SelinaBuff** [comment]
Done! 
We just have to revise the menu bar for mobile (#3236)

**Comment by SelinaBuff** [comment]
mobile menu bar (#3236) is done 👍

The Design for the reactions is now completely done!
