### ISSUE TITLE
Cannot create new card with enter on Android

### ISSUE THREAD

**Issue by CronJorian** [inovex/scrumlr.io#1792]
When pressing enter after typing in the input field, the right button will be pressed instead of the submit button of the input field.
So you can only submit cards by pressing the + button on mobile

https://user-images.githubusercontent.com/44020029/172837360-b63623a2-dadf-4c5f-82a7-746feceb91ab.mp4

**Comment by brandstetterm** [comment]
This seems to be an issue with Android phones. On my iPhone, I was just able to create notes with pressing enter.
