### ISSUE TITLE
Arrow colors are inconsistent

### ISSUE THREAD

**Issue by timengel** [inovex/scrumlr.io#1807]
When 3+ columns are shown on screen, the left arrow follows the color of the left-most column while the right arrow follows the colors of the currently focused column.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32651718/173256081-fd7de5ff-0788-48e9-9f65-7165c7ebd23a.png">

**Comment by Kraft-16** [comment]
https://xd.adobe.com/view/e8c7871a-f8c4-4a55-af0f-ac39b7ea4616-bd94/

**Comment by bitionaire** [comment]
Duplicate of #1251 since we're moving the arrows to the action bars
