### ISSUE TITLE
Refactor note stack view

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#1817]
AC:
- Stack view has been implemented according to the new design
- Focus view has been implemented according to the new design
- Both views are accessible via links (e.g. `/board/<board-id>/<note-id>` for stack view, `/board/<board-id>/<note-id>/focus` for focus view)
- Meaningful tests have been written

**Comment by bitionaire** [comment]
AC (extended):

- Close button added
  - Close (or click on backdrop) does not stop the sharing of a note. Instead the moderator must end the focus mode to stop sharing. This will enable the moderator to do something else (e.g. write an action note) while sharing 
- Added button to maximize view (increased font-sizes, ...)
- Switch to previous/next stack
  - Add buttons to switch to previous/next stack
  - Swipe on mobile devices to switch
  - Hotkey arrows (left/right) to switch to next/previous stack
- Redesign of action buttons on notes
- Added dot indicators for notes in column
- Highlight shared/focused note in regular board view

Bonus:
- Add textual hint that a note is shared with others while in focus mode

**Comment by bitionaire** [comment]
Design export required

**Comment by bitionaire** [comment]
@Kraft16 can you post a link to the final design concept of the stack view? Thank you!

**Comment by Kraft-16** [comment]
Stack View: 
Dark Mode:
https://xd.adobe.com/view/1b6fac62-e701-4205-8841-b1b74586c0e0-4e3c/
Light Mode:
https://xd.adobe.com/view/f6a7e159-4f11-46f9-9663-4f69923bb141-a3f4/
Dark Mode, different collors:
https://xd.adobe.com/view/e1e72fa0-beab-4c3b-b52c-f7a18bbc0fcc-b4b4/
