### ISSUE TITLE
Enhance Appearance Settings

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#1820]
At the moment the Appearance settings view seems kinda unfinished. We should think about a new design for this view.
![Screenshot 2022-06-15 at 09 34 09](https://user-images.githubusercontent.com/36969812/173769734-2b10c931-6118-4dd5-8bbd-cc7c32caf291.png)

AC:
- [ ] Refactor appearance settings (see below)
- [ ] Automatically choose theme based on system settings

Template:
![Image](https://user-images.githubusercontent.com/32651718/182367194-2e499de9-1c62-4afd-affd-01d81e60feb5.png)

Ideas: 
- add sun 🌞 and moon 🌙  icons
- currently selected option is made clear, e.g. border, checked icon,...

**Comment by Resaki1** [comment]
![Bildschirmfoto 2022-07-05 um 13 51 59](https://user-images.githubusercontent.com/35272402/177321442-0492b9c3-3ae2-4145-a034-15d1ce5ffe5f.png)
Maybe something like this?

**Comment by timengel** [comment]
Ideas: 
- add sun 🌞 and moon 🌙  icons
- currently selected option is made clear, e.g. border, checked icon,...

**Comment by brandstetterm** [comment]
Done ✅
