### ISSUE TITLE
SPIKE: Evaluate alternative backends to Firebase

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#183]
* https://parseplatform.org - Documentation is hard to read & not sufficient in details (e.g. pointer permissions) / features seem to be sufficient for our use-case / large community and in active development *=> worth further investigation*

No option:
* ~~https://appwrite.io~~ - Small community / in active development / lightweigt & with potential
* ~~https://www.back4app.com~~ - Just a wrapper for parse / no options for on-premise setups
* ~~http://hood.ie~~ - Small community / rarely updates
* ~~https://github.com/rethinkdb/horizon~~ - Small community  / rarely updates
* ~~https://github.com/pubkey/rxdb~~ - Only DB, no sophisticated mechanisms for authentication & authorization

**Comment by hloeffler** [comment]
What is the goal?

I for myself just want to use this super useful tool inside my company without any external dependencies.
I don't need any persistence at all.

(And yes, firebase sound aweful)

**Comment by bitionaire** [comment]
Hey @hloeffler, you need some sort of persistence to exchange data. In many teams P2P based exchange only is not enough, because many of the boards are created and used in advance of the actual session of the team. :) 
Firebase is currently handling the authentication and the web-socket based data synchronization, as well as the access logic itself. We came to the conclusion, that we would like to continue developing on the firebase platform. 
If security is one of your concerns you should always try to use the "private" mode upon creation of sessions, as it will ensure that all data is encrypted and cannot be read by either Google or the admin team behind Scrumlr. 👍
