### ISSUE TITLE
Split repositories

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1834]
Split repositories into...

- _scrumlr.io-client_
- _scrumlr.io-server_
- _scrumlr.io_ (root repository includes the other repos as submodules)

This should improve the performance of our CI and also we'll be able to develop separate versions.

**Comment by brandstetterm** [comment]
I've already tried how this could be done without losing our entire commit history. Seems like [git-filter-repo](https://github.com/newren/git-filter-repo) is a great tool for that
