### ISSUE TITLE
Automation of infrastructure

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1846]
Als Plattform-Admin möchte ich ein das Deployment der Infrastruktur automatisierten

*Akzeptanzkriterien:*
* Infrastructure as Code ist vorhanden (z.B. mit terraform)
* Deployment ist über eine (Gitlab-/GithHub-) Pipeline automatisiert
* Deployment ermöglicht schnelles aufsetzen einer weiteren Staging-Umgebung
* Einfacher wechsel auf z.B. neue Kubernetes-Version ist möglich

**Comment by Lennart01** [comment]
Partly finished. Rest will be tracked in #2366
