### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1847]
Als Plattform-Admin und Entwickler möchte ich meine Infrastruktur und Applikationen mit einem State-Of-The-Monitoring-Stack verwalten können.

*Akzeptanzkriterien:*
*Metrics-Server ist in Kubernetes installiert
*Prometheus ist installiert und sammelt automatisch Kubernetes Metriken ein
*Grafana ist installiert und visualisiert den Cluster-Status

**Comment by Lennart01** [comment]
Implemented
