### ISSUE TITLE
Provide easy way to selfhost -> Dockerimage?

### ISSUE THREAD

**Issue by hloeffler** [inovex/scrumlr.io#185]
Can you please provide an Dockerimage for easy self hosting?

**Comment by bitionaire** [comment]
Hi @hloeffler,

we've added the Docker image build to our current version of scrumlr.
You can checkout the image @ https://github.com/inovex/scrumlr.io/packages/178571
If you have any problems settins up your container please give a feedback :)

**Comment by hloeffler** [comment]
Thanks, got it running with this:
https://github.com/inovex/scrumlr.io/blob/v1/Dockerfile
