### ISSUE TITLE
Moderator can start a timer for the team

### ISSUE THREAD

**Issue by brandeins1403** [inovex/scrumlr.io#194]
As a moderator, i want to start a timer, which is shown to every user, in order to set a time frame for a part of a meeting

AC:

----

- On hover effect is shown
- Minutes can be setup (default 5 minutes)
- Timer can be set click and pull

Tasks:

- [ ] Create timer button in admin side menu
- [ ] Create hover effect
- [ ] Create FE for setting up timer using click and pull

**Comment by bitionaire** [comment]
Blocked by #220
