### ISSUE TITLE
Implement redesign of timer and remaining votes indicators

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1955]
To further clarify some design details that aren't self explanatory by the exported design:

* The timer / alarm sound should be played once 3 sec. are left on the timer
* The font color should turn to red once 10 sec. are remaining
* We think the "10+ min." title fits best if the timer length is greater 10 mins.

Tasks:
- [x] Implement redesign of vote display
- [x] Implement redesign of timer

**Comment by Kraft-16** [comment]
indicators states: https://xd.adobe.com/view/7f0566cb-b200-455d-bfb0-7c557d0262fa-2a56/
Light mode: https://xd.adobe.com/view/1fe8b588-5327-4060-a22d-eb27962a3e07-4abb/
Dark mode: https://xd.adobe.com/view/519245f0-e530-4fdf-89b7-a6d9c5602454-04c1/

**Comment by brandstetterm** [comment]
The start time / date of a timer has to be saved for the timer progress bar. Therefore, we have to modify our database & backend before implementing the redesign of the timer. 

Tasks: 
- [ ] Modify database to save the start time for timers of boards
- [ ] Modify backend api, services, etc.
- [ ] Modify frontend to send & receive both start & end time
- [ ] Implement redesign (change component, styling, etc.)
