### ISSUE TITLE
Moderator can hide authors of the sticky notes

### ISSUE THREAD

**Issue by brandeins1403** [inovex/scrumlr.io#196]
As a moderator i want to hide the authors of the cards to give them the privacy they need, to express themselves openly in a discussion

AC:

- Hiding user name and avatar can be toggle in moderator bar
- Own stickys are still flagged by border to the users 

Tasks:

- [ ] Button is implemented in admin menu
- [ ] flag is implemented in "board" table
- [ ] authors are hidden in frontend, when option is activated

**Comment by bitionaire** [comment]
Blocked by #225

**Comment by bitionaire** [comment]
https://projects.invisionapp.com/d/main?origin=v7#/console/20620074/433365958/preview?scrollOffset=0
