### ISSUE TITLE
Dark mode can be activated

### ISSUE THREAD

**Issue by brandeins1403** [inovex/scrumlr.io#197]
As a user i want to activate the dark mode, because its fancy

AC:

- Dark mode settings are fetched from os settings
- Dark mode can be (de)activated in user menu under settings
- Dark mode setting is used in my next sessions

Tasks:

- [ ] Frontend Darkmode Context Theme Switcher bereitstellen
- [ ] Dark Mode Toggle Funktionalität bereitstellen
- [ ] Dark Mode Einstellungen im Cookie / Local Storage speichern

**Comment by bitionaire** [comment]
https://github.com/GoogleChromeLabs/dark-mode-toggle can be probably used here
