### ISSUE TITLE
Application icons in different resolutions

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1978]
In order to close #1810 we need proper application icons (for mobile devices) in different resolutions and in PNG format.

The resolutions are:

* 196x196px
* 32x32px
* 16x16px
* 180x180px
* 167x167px
* 152x152px
* 70x70px
* 150x150px
* 310x150px
* 310x310px

**Comment by Kraft-16** [comment]
[PNG.zip](https://github.com/inovex/scrumlr.io/files/9494987/PNG.zip)
