### ISSUE TITLE
Add overview of all automations

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#2057]
As a user (and a developer), I want to see an easy-to-understand overview of all automations of my scrumlr session, i.e. "remove ready-state of all users when timer is over" or "set user ready when user has casted all votes". This adds more transparency and makes it easier to understand.
Additionally, it would be nice if those automations could be enabled/disabled. In the future, users could create new automations and we could offer premium automations.

**Comment by SelinaBuff** [comment]
- maybe like our cheat sheet (a document with all explained features)
