### ISSUE TITLE
Removing notes with votes doesn't remove the votes from total vote counter

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#2065]
If a user casts a vote on a note and that note is deleted, the total vote counter doesn't change. The same goes for votes that are removed because the column is deleted.
This can lead to scenarios like the following, where the user has casted e.g. 2 out of 5 votes, even though they should still have 5 free votes:

![Image](https://user-images.githubusercontent.com/35272402/184860261-9beefa15-d09e-4799-98d6-30b440afd9d6.png)

**Comment by Schwehn42** [comment]
I looked into this, and apparently the API/actions only support adding/removing a vote one at the time.  
Now you could call the `deleteVote` action for each vote that was removed by a deleted note, resulting in multiple backend calls as well.
Should we add the functionality to remove multiple votes first? or just do it iteratively for now
