### ISSUE TITLE
Implement redesign of raised hand notification dialog

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2085]
To further clarify some design details that aren't self explanatory by the exported design:

- Width of the notifications should be defined by the length of the usernames

**Comment by Kraft-16** [comment]
https://xd.adobe.com/view/161672d3-fa43-4a37-9832-e596ea512e3a-4345/

**Comment by Schwehn42** [comment]
how is this supposed to behave when multiple people are raising their hands at the same time? currently, they're stacked on top of each other in the same notification which is stretched in its height. seperate notifications would be better wouldn't they?

**Comment by Kraft-16** [comment]
https://xd.adobe.com/view/ca79875f-7c71-4ea7-b9f9-d3932098ce2e-9f2a/
when several people raise their hands at the same time, the notification appears below the previous window.

**Comment by Kraft-16** [comment]
New Redesign: https://xd.adobe.com/view/827e788e-2f09-465f-9a2a-ff59f7362acc-d72d/
