### ISSUE TITLE
"Mark as Done" button stays active when switching modes

### ISSUE THREAD

**Issue by rlirli** [inovex/scrumlr.io#2147]
After the current redesign, the "Mark as Done" button stays active, when switching from creating cards to voting mode. It should be reset instead.

**Comment by CronJorian** [comment]
Voting should not be perceived as a phase/mode like in scrumlr v1 and therefore the ready state will not be automatically reset. But there will be an option for moderators to reset the ready state if they want to (which is already in work) 🙂
