### ISSUE TITLE
Scroll column is also displayed correctly in Safari

### ISSUE THREAD

**Issue by alphapfote** [inovex/scrumlr.io#221]
As a user, I want the navigation to be displayed correctly in the Safari browser.

AC: 
- Scrolling is fixed and shown displayed correctly.

The navigation currently uses scrollIntoView. However, scrollIntoViewOptions are not supported by Safari: https://developer.mozilla.org/de/docs/Web/API/Element/scrollIntoView
To solve the problem, scrollTo should be used instead.  

Tasks: 
- [ ] Use scrollTo to fix the scrolling.
- [ ] Insert a comment, as scrollIntoViewOptions may be supported by Safari in the future and can therefore be used again.

**Comment by brandstetterm** [comment]
So I've tried both `.scrollTo()` & `.scrollBy()`. Sadly, both are jumping to the given coordinates like `.scrollIntoView()` 😢 So I guess there's nothing we can use for Safari to have a smooth scrolling effect
