### ISSUE TITLE
Implement stack view navigation bar

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#2229]
As a user I want to navigate between stacks in one column from inside the stack view.

Design:

![Image](https://user-images.githubusercontent.com/35272402/194528282-4c9a7c49-57de-4d0a-9f23-7690fb4d7f3a.png)

**Comment by Kraft-16** [comment]
https://xd.adobe.com/view/f5a8e544-90dc-4365-86bf-522169239630-a0fb/
