### ISSUE TITLE
Show assignee of note in actions column

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2256]
* Assignee can be one of the participants or the name can be defined by a text field

**Comment by brandstetterm** [comment]
Before this can be implemented properly in the frontend, a designer should invest some time and design something beautiful :) 

Also, we should think about how we want to display multiple things / bits of information in the footer of our notes. One idea could be to only display the most important things by default and everything else / less important will be displayed on hover. If this is the best possibility, we need to clarify what's most important to display first. 


Example (stolen from GitHub) how it could look like:
![Image](https://user-images.githubusercontent.com/36969812/233041791-a6f8acf3-db1a-4109-8a40-24a18566aba8.png)
![Image](https://user-images.githubusercontent.com/36969812/233041792-2c352f3c-dc2e-435f-be08-abeda89a84ea.png)
