### ISSUE TITLE
"Back to focus card" button doesn't have a dark mode design

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#2257]
![Image](https://user-images.githubusercontent.com/35272402/195167796-6b1fe2a8-c4aa-44a9-9817-8f6fbf2c7c99.png)

**Comment by brandstetterm** [comment]
The "Back to focus card" button does have a light & dark mode theme. The reason it looks so odd besides the votes counter is that the new design of the counter & timer hasn't been implemented yet.
