### ISSUE TITLE
Adjust icons

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#2304]
Anbei die aktualisierten Icons in gleicher Linienstärke für dark- und lightmodus jeweils als png & svg.

[Scruml_icons_update_27102022.zip](https://github.com/inovex/scrumlr.io/files/9879830/Scruml_icons_update_27102022.zip)

**Comment by bitionaire** [comment]
Steps todo:

- Minify SVG
- Replace color hex codes with `currentColor`
- Viewbox review (should be identical in all icons)
- Embed new versions of icons in code

**Comment by bitionaire** [comment]
https://github.com/inovex/scrumlr.io/pull/2468

**Comment by SelinaBuff** [comment]
Icons have been updated:


[Scrumlr_Icons_09062023.zip](https://github.com/inovex/scrumlr.io/files/11707131/Scrumlr_Icons_09062023.zip)
