### ISSUE TITLE
Toggling focus mode while viewing a note leads to inconsistencies.

### ISSUE THREAD

**Issue by CronJorian** [inovex/scrumlr.io#2310]
**Using the hotkey (f) to toggle the focus mode leads to inconsistencies while viewing a note.**

1)))) _Expected behavior:_
Open the note for others as well, when activating the focus mode while on a note.

_Actual behaviour:_
Nothing happens. The user has no option to see the focussed note.

---

~~_Expected behavior:_
Participants cant activate focus mode

_Actual behaviour:_
The hotkey changes the border in the stackview to the focus mode color.~~

---

2)))) _Expected behaviour:_
Disabling and enabling the focus mode captures everyone in focus mode again, even after users left the focus mode (TL;DR: focus mode is broken on second time of usage).

_Actual behaviour:_
Just the "back to the focussed note" appears.
After clicking on it, the participant is just viewing the momentarily focussed note, if another note is viewed by the moderator, the note does not change.

---

3)))) Schliessen als Moderator schliesst nicht die Detail View der Participants
4)))) Focus mode wird beendet während man in Detail View ist und das Icon (zurück zum Focus Mode) verschwindet nicht
5)))) Der Moderator bekommt die einblendung vom Icon (=zurück zum Focus Mode) was durch den Backdrop scheint -> Icon muss weg

**Comment by bitionaire** [comment]
Opened issues #2342 , #2343, #2344, #2345, #2346 in order to split different tasks as described within this issue
