### ISSUE TITLE
Focus mode does not work when triggered for the second time

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2343]
Currently the focus mode is not working properly when triggered for the second (... third, n-th time). The button to open a shared note will be displayed to participants but the notes won't be opened automatically if the moderator starts to change the detail view of a note.

**Comment by Resaki1** [comment]
I can't reproduce this bug, it seems to work perfectly for me. Can you give a more detailed explanation on how to reproduce this?

**Comment by CronJorian** [comment]
This was in the context of the usage of the hotkey. But I can't reproduce it either anymore, so I guess it either got fixed or I did something wrong.
