### ISSUE TITLE
Enhance performance by query pagination

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#237]
As a user I want a very responsive user experience.

AC:
- The Parse Querys are (probably) limited to 100 objects in one response and therefore pagination should be added (e.g. with the help of the `.withCount()` method on queries)

**Comment by brandstetterm** [comment]
I discovered recently that you can increase the default Query limit of 100 objects by using `Query.findAll({batchSize: <number_of_objects>})`. However I don't know if it also works for more than 1000 objects
