### ISSUE TITLE
Change german "Registrieren" button

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2380]
The combination of the description "No registration required" and the german "Registrieren" as the CTA is somewhat confusing and should be replaced with a better action name.

e.g. "Jetzt loslegen", "Starten", "Auf gehts!" ... _[your idea]_

**Comment by Schwehn42** [comment]
Should the title above reading "Registrierung bei scrumlr.io" also be changed to something else, like "Login bei scrumlr.io"?

**Comment by Schwehn42** [comment]
I also noticed that in the English version, when leaving the username empty it reads "Username may not be empty", I think "must not" is even clearer according to https://www.ietf.org/rfc/rfc2119.txt ^^ but this is very picky of me
