### ISSUE TITLE
Create a note in a different column (e.g. Actions column) from stack view

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2383]
As a moderator I want to create a note in another column while I'm presenting a note (in the stack view). E.g. I want to create an action note while the team is discussing a topic.

**Comment by SelinaBuff** [comment]
Idea: Button (create note) / Position: unclear

![Image](https://user-images.githubusercontent.com/116653219/225032023-d02d7d23-fdc1-44d9-8059-06efe17a49fe.png)
