### ISSUE TITLE
Show number of total votes spent for moderators (alternative way to "ready" state)

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2385]

**Comment by brandstetterm** [comment]
Things to consider:
- Do we want to publish the number of spent votes via the public web socket channel? 
- Do we want to make it "spy proof" and create a dedicated web socket channel only for moderators

**Comment by brandstetterm** [comment]
Ideas:
If the participant has the role MODERATOR or OWNER, connect to a dedicated ws channel for moderators.
Authentication could be done by sending the credentials (user id) with the first ws message (onconnect).
If authentication fails, the server closes the connection.
This way we could prevent spying on the things that are exclusive to the moderators (e.g. hidden notes, total votes spent).
