### ISSUE TITLE
Presenter looses his presenter status on page reload

### ISSUE THREAD

**Issue by CronJorian** [inovex/scrumlr.io#2393]
- Start focus mode
- Open a Note
- Press F5 / cmd/ctrl + R
- ???
- Profit

**Comment by bitionaire** [comment]
As discussed: Selection of presenter mode state should be persisted.

Option a (reconnect within 15 min.) -> presenter mode stays active
Option b (reconnect later, at any time) -> show dialog whether users wants to join with presenter mode

@brandstetterm did not approve, yet we will implement it this way
