### ISSUE TITLE
It's possible to spy on the hidden notes (in hidden columns) via the network tab in the dev tools  

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#2433]
<img width="1491" alt="Screenshot 2022-12-01 at 16 10 31" src="https://user-images.githubusercontent.com/36969812/205091203-92db785c-e285-4f73-860e-f06f4e6a8b9d.png">

**Comment by bitionaire** [comment]
User should only receive data he is allowed to see based on the board settings (e.g. show notes of other users, show hidden columns, ...)
