### ISSUE TITLE
Can't set theme to light on MacOS (only on prod?)

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#2489]
I can't set the theme to light on MacOS:
https://user-images.githubusercontent.com/35272402/206860687-c58d93e7-cbed-467a-8826-18ab5df91a2a.mov

Doesn't work in:
- Safari for MacOS
- Chrome for MacOS
- Firefox for MacOS

Works in:
- Safari for iOS
- Chrome for iOS
- Firefox for iOS

Strangely, this only seems to be the case on the live environment, not when hosting locally, so it's hard to diagnose. Can someone test this on Windows please?

**Comment by bitionaire** [comment]
Works on Windows and Chrome 🤷‍♂️

**Comment by CronJorian** [comment]
Works on MacOS and Chrome too

**Comment by Resaki1** [comment]
> Works on MacOS with Chrome, Safari and Firefox too. Can you try to reproduce it?

Still doesn't work for me. What MacOS version did you try this on?

**Comment by CronJorian** [comment]
Did just test it again.
Works fine, the button is clickable and works as expected.

MacOS Ventura 13.0
Chrome 109.0.5414.87
Scrumlr.io 2.8.1

**Comment by Resaki1** [comment]
Closing this as it works for me now as well.
