### ISSUE TITLE
Redirect to stack URL when note is moved into stack

### ISSUE THREAD

**Issue by CronJorian** [inovex/scrumlr.io#2509]
Currently when in StackView and the viewed note gets moved into a stack (while not being the parent note), the URL does not change and the StackView is showed as if the viewed note is the parent note (aka. the note is not stacked).

I think it would be intuitive to redirect to the StackView URL so that the current state of the note is mirrored (as in "the note becomes a child note in a stack")

**Comment by bitionaire** [comment]
- On Stack: Redirect to parent stack and show toast "Card was moved" (something like that)
- On Deletion: Leave stack view and show toast "Card was deleted" (or something like that)
