### ISSUE TITLE
Note in stack view should show more (... or complete?) content

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2627]
As a user I want to see the complete (... or more of the) text of a note in the detail/stack view, if theres enough space available on my screen.

_Alternatives how we could address this:_
- Maybe add expande/collapse toggle (to all notes)?
  - Show expanded state if theres only one note
  - Show collapsed note if there are multiple children in the stack
- Increase space for parent note?
- Show complete text and include parent note into the scrollable area?
- Redesign the screen and put parent note on one side and the children on the other side?

**Comment by Kraft-16** [comment]
New Design Stack view:
https://xd.adobe.com/view/1bdd7208-4f56-462f-8bd3-cbf3f36249f3-4e8e/

**Comment by Kraft16** [comment]
improved design:
https://xd.adobe.com/view/9c39ca3a-b4a6-4dfe-ba4e-e0d075a9acc6-c96a/

**Comment by bitionaire** [comment]
Hey @brandstetterm can you check whether you closed this issue on purpose or by accident? I did not find another issue related to this topic

**Comment by brandstetterm** [comment]
Yes, I think that was by mistake because I confused it with another issue @bitionaire

**Comment by Schwehn42** [comment]
I put this back into Todo because of time issues 🥲
