### ISSUE TITLE
Grow note input by the content (support multiline for easier navigation)

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2630]
As a user I want to see my complete text in the note input and the input field should grow by it's content. The plus icon should stay at the top while the input field is growing. The transition should be nicely animated.

This does not mean that we want to introduce multiline text and linebreaks should still not be available in the note input.

**Comment by SelinaBuff** [comment]
![Image](https://user-images.githubusercontent.com/116653219/224949763-f3dbecba-6c48-47e0-89f7-b77b6075cc7f.png)
