### ISSUE TITLE
Reduce the gap between the voting buttons

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#2740]
### Currently (12px gap):
![Screen Shot 2023-03-07 at 16 05 56](https://user-images.githubusercontent.com/36969812/223461994-b9fc5aba-2d04-469f-8669-e1a71d33cb92.png)

### Proposal:

- 8px
![Screen Shot 2023-03-07 at 16 10 25](https://user-images.githubusercontent.com/36969812/223463269-512c4a76-f354-43a9-a9bc-7cadf3a18ee2.png)
- 6px
![Screen Shot 2023-03-07 at 16 11 25](https://user-images.githubusercontent.com/36969812/223463532-503ad0a1-feae-4607-ac53-020c62eb6483.png)

- 4px
![Screen Shot 2023-03-07 at 16 07 29](https://user-images.githubusercontent.com/36969812/223462449-95a9797f-64af-44a2-9f2e-525028af761f.png)

**Comment by bitionaire** [comment]
6px gap looks good
