### ISSUE TITLE
Fix hotkey cheat sheet

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2762]
**User Stories:**

> 1. As a user, when I press "SHIFT + /" on my English keyboard layout, the hotkey toggle should be triggered to open the hotkey manual, as specified in the cheatsheet. This functionality needs to be fixed.
> 
> 2. As a user, when I press "CMD + U," I expect to see the notes of other users. Currently, only "CTRL + U" is working, which is not the intended behavior.
> 
> 3. As a user, when I press "CMD + J," I expect to be able to show hidden columns. Currently, only "CTRL + J" is working, which is not the intended behavior.
> 
> 4. As a user, when I trigger the settings dialog with the "S" key, it should also close the dialog if it's already open.
> 
> 5. As a user, when I trigger the voting dialog with the "V" key, it should also close the dialog if it's already open.
> 
> 6. As a user, when I trigger the timer dialog with the "T" key, it should also close the dialog if it's already open.
> 
> Additionally, after issue #3357 is merged, the following functionality should be added:
> 
> 7. As a user, when I press the "R" key, it should trigger a board reaction.

**Comment by Schwehn42** [comment]
also add 'R' for board reaction when #3357 is merged

**Comment by Kraft16** [comment]
Cheat sheet updated:

https://xd.adobe.com/view/3ae1c2bc-1238-4f10-a8e2-1ae7c6fe5c21-6fb2/
