### ISSUE TITLE
Add space for meeting notes

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2798]
As a moderator I want to write down a few meetings notes (e.g. list of participants or some high- and lowlights of a meeting). Additionally to the custom board title I might set I want another space where I can add those.

**Comment by SelinaBuff** [comment]
*Idea

![Image](https://user-images.githubusercontent.com/116653219/234576203-ebce6d1b-8585-49b1-8210-c3c548e65640.png)
