### ISSUE TITLE
Design landing page / homepage

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#280]

**Comment by SelinaBuff** [comment]
Landingpage ist fertig!

[Hier](https://www.figma.com/file/8m2V6OJTImuOdQoxruWurP/Scrumlr-Landingpage?node-id=0%3A1&t=1znmROL00nSsmn6M-1) geht es zu Figma.

[Hier](https://drive.google.com/drive/folders/17tl_RSzxUORu3DR9lWQQ1f1dTkIpCoQy) der Link für die Grafiken.

Sollten Fragen oder Anmerkungen aufkommen, bitte direkt bei Figma kommentieren oder bei mir melden.
