### ISSUE TITLE
Landingpage_ Section 7 (Caroussel)

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#2845]
[Link for Figma](https://www.figma.com/file/8m2V6OJTImuOdQoxruWurP/Scrumlr-Landingpage?node-id=0%3A1&t=1znmROL00nSsmn6M-1)

[Link for Visuals ](https://drive.google.com/drive/folders/17tl_RSzxUORu3DR9lWQQ1f1dTkIpCoQy?usp=sharing)

![Image](https://user-images.githubusercontent.com/116653219/230435947-c4a56456-c332-4b31-aedd-ab61215a0150.png)

**Comment by SelinaBuff** [comment]
Unser erstes, offizielles Kundenfeedback:

Scumlr macht Retrospektiven zu einem Event! Man freut sich immer wieder drauf. Schönes Design und einfache Bedienung. Ich bin ein absoluter Fan.

Amelia Febrer
CEO, Regardi

**Comment by SelinaBuff** [comment]
**2.** 

Scrumlr hat mich seit der ersten Nutzung begeistert! Das Tool ist aus meinem Arbeitsalltag nicht mehr wegzudenken und ich kann es nur jedem empfehlen, der  auf agile Arbeitsweisen setzt. 

Filip Lukenic
Produktmanager

**Comment by SelinaBuff** [comment]
3. 

Dank der Einfachheit und den Möglichkeiten von Scrumlr können wir effektive Retros auch ohne dedizierten Moderator durchführen.

Yann Carpy
Product Owner, inovex

**Comment by SelinaBuff** [comment]
**4.** 

Scrumlr ist das perfekte Tool für spontane Retros: Es ist sehr leicht zu benutzen, hat eine niedrige Einstiegshürde und die coolsten Avatare ever!

Melanie Laudin
Usability Engineer

**Comment by brandeins1403** [comment]
Ich meiner tägliche Arbeit als Agile Coach unterstützt mich scrumlr optimal bei jeder Retro. Die Boards geben uns stets eine tolle Struktur und der spielerische Ansatz regt zu einer positiven Interaktion der Teilnehmer an. Ich würde auch Geld für die Nutzung bezahlen. Weiter so. :)
