### ISSUE TITLE
Evaluate simple headless CMS options

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2848]
Pick a good documented and lightweight headless CMS i.e. for the content of our landing page and the board templates.

- The CMS should be able to scale, either by the database configuration or in itself
- The CMS should at least have an API that can be used to create a script for the initial data (ideally it has an option to import a configuration on start and check for missing/outdated properties)
- The CMS should be able to support multiple languages
- The CMS should have a solid userbase and a good perspective for updates and maintenance
- The CMS should run on our own infrastructure and not within an own cloud
- The CMS should be well documented and easy to use (great developer experience)
- Ideally it supports Postgres for persistence so that we can use our current cluster

Out of the box Strapi and Payload CMS seem to be very promising. I'd like to try Playground CMS since it seems to be even fresher and I can't think of a project where it's in use right now. Feel free to look for further options

**Comment by BenedictHomuth** [comment]
## Update & Conclusion of searching for a CMS
After trying out a couple of (un-) popular CMS vendors, there is the following conclusion:
Choosing a CMS is not a trivial task, and there are benefits for each vendor in some way over another...

However, I want to give a short insight into why we did not go for the following vendors:

### Strapi CMS
Strapi checks a lot of boxes, but one major criticism is that SSO is only accessible behind a paywall. Also, the UI – at least for me – is very similar to WordPress.

### WordPress
Not really liked by developers. Old and rusty in my view, but still used in many projects.

### Payload CMS
A developer-first CMS. Great if you want to build everything from scratch yourself. But... you need to build everything from scratch, including SSO and so on. Even though we have the skills for developing all of this in our team, I feel it would be more of a burden than a benefit overall (One more thing to maintain – also not the main focus of our own project). Lastly, Payload CMS does not support other databases besides MongoDB as of this writing.

### Others
There are many more options out there, including but not limited to Contentful, Prepr CMS, Tina CMS...
All of them are great for specific use cases but are lacking some of our core requirements. Most often, one of the following:

- Self Hostable
- Postgres support
- Regular Updates (Often infrequent updates or tiny community – unforeseeable future of the project)


---

# Our Choice

## Directus
[Directus](https://directus.io/) checks all boxes of our requirements. It is:
- Self hostable
- Scalable (via Redis)
- Makes it easy to integrate SSO
- Offers API endpoints (REST and GraphQL)
- Backed by a huge userbase (~22.6k GitHub Stars, 10k Discord Members, established in 2004, regular updates)
- Postgres compatible (and many more)
- Supports multiple languages
- Open Source and can be extended when the need is there
- ...


After trying it out locally and also on a k8s cluster, it was an overall great developer experience. Directus is easy to set-up and contains a straightforward documentation. 

Scaling works with Redis and only needs a connection string to be passed as an env-var. The same is true for the database and SSO.

The API works as expected, and the "Flows" and "Webhook" options are good for further customizing or automating data flows and events.
