### ISSUE TITLE
Change icon of join request toasts

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#2853]
Right now the toast for somebody raising their hand and the toast for someone requesting to join the session have the same icon. I think we could use a different icon that's better suited for the join request toasts. 

![Image](https://user-images.githubusercontent.com/36969812/230683579-736e6e22-37ae-4de5-ab31-ff8936c5c7a4.png)

Example of icon that could be better suited:

![Image](https://user-images.githubusercontent.com/36969812/230683708-b1c11e83-6eca-4fed-9914-70cdadd0f754.png)

**Comment by SelinaBuff** [comment]
*create new Icon

**Comment by Kraft16** [comment]
Toast (Join):
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1725%3A29977&type=design&node-id=2934-19213&viewport=-19306%2C2007%2C0.54&t=DAXptJOL2MFrX540-1&scaling=min-zoom&starting-point-node-id=1729%3A36833&show-proto-sidebar=1&mode=design
