### ISSUE TITLE
Automatically deploy most recent commit on main to development.scrumlr.fra.ics.inovex.io

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#2856]
I think it would be cool if the most recent commit on the main branch would automatically be deployed to https://development.scrumlr.fra.ics.inovex.io/. This would allow us to test the latest commits before, for example, we publish a new release.

**Comment by Resaki1** [comment]
related: https://github.com/inovex/scrumlr.io/issues/2882
