### ISSUE TITLE
Add option to display important/urgent messages

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2868]
As a user I want to read about important or urgent messages, e.g. a downtime announcement for maintenance reasons or in case of issues with the database. 

- The message can be defined at runtime
- The duration of the message to display can be configured (start and expiration)
- The message will be displayed noticeably to the user 
- The user must ack the message in order for it to disappear

**Comment by SelinaBuff** [comment]
Design: Pop up Dialog
