### ISSUE TITLE
Fix caching issue of service worker that prohibits the 3rd party authentication

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#2871]
Every user who opened v3.2.0 of Scrumlr has a cached version of the service worker (PWA) that prevents the 3rd party authentication with a 404 error. We need to find a way to invalidate the cache

**Comment by Resaki1** [comment]
Not sure, but the problem might be that we simply deactivated the service-worker. Because of that, the old (faulty) one simply keeps existing and serving content from cache. Deploying an update with a new service-worker which either works or just doesn't cache anything might fix this.
