### ISSUE TITLE
Enable Stacked Cards to be unstacked again

### ISSUE THREAD

**Issue by bontscho** [inovex/scrumlr.io#3]
When stacking cards, I would like for an option to unstack a card so it stands as a single card again

Thank you very much and keep up the good work

**Comment by brixtonasias** [comment]
That would have come in handy today. So +1 for the feature. ;-)

**Comment by bitionaire** [comment]
Cards can be unstacked by clicking on a stack and using the "Unstack" button on the details view :) 
Right now only admins can unstack cards and we will open a new issue that will allow everybody to unstack cards 👍 

![Screenshot 2021-07-21 at 17 49 12](https://user-images.githubusercontent.com/1539948/126602265-d62c430a-930e-4abe-ac8b-2f329f7639ac.png)

**Comment by bitionaire** [comment]
#543 :)
