### ISSUE TITLE
Settings: Can't (re-)select light theme

### ISSUE THREAD

**Issue by Schwehn42** [inovex/scrumlr.io#3054]
When changing theme, it's not possible to reselect the light theme.  
_Auto_ and _Dark_ still works as intended.

**Comment by brandstetterm** [comment]
It works for me flawlessly. Can you add some additional information which browser you are using and steps to reproduce? @Schwehn42

**Comment by Schwehn42** [comment]
not sure anymore whether this was on dev only, or maybe the issue resolved itself. anyways gonna close the issue
