### ISSUE TITLE
No error notification for entering a wrong password (color control)

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#3096]
As a user, I expect to receive visual feedback (toast) if I have entered my password incorrectly.

**Comment by Kraft-16** [comment]
new design:
light mode: https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=2790%3A33189&type=design&node-id=2894-36698&viewport=-15160%2C1397%2C1.04&t=Dt8VLf3oAQ2wjIwP-1&scaling=min-zoom&starting-point-node-id=2894%3A36698&mode=design
dark mode: https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=2790%3A33189&type=design&node-id=2894-37407&viewport=-15160%2C1397%2C1.04&t=Dt8VLf3oAQ2wjIwP-1&scaling=min-zoom&starting-point-node-id=2894%3A36698&mode=design

**Comment by Kraft-16** [comment]
new design:
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=2790%3A33189&type=design&node-id=2894-40386&viewport=-2624%2C665%2C0.28&t=BhZAw6zktBy0cz0K-1&scaling=min-zoom&starting-point-node-id=2894%3A36698&mode=design

**Comment by Kraft16** [comment]
Popup (Password) New:
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1725%3A29977&type=design&node-id=2934-19217&viewport=-22298%2C2330%2C0.7&t=tDgUeWZ1Qia4MJoz-1&scaling=min-zoom&starting-point-node-id=1729%3A36833&show-proto-sidebar=1&mode=design

**Comment by Resaki1** [comment]
@Kraft16 I think the first link is broken. Could you post it again?

**Comment by Kraft16** [comment]
thanks @Resaki1 for the reminder. Here's the actual link to the design.

Popup (Generate password):
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1725%3A29977&type=design&node-id=4051-31455&viewport=-16948%2C2274%2C0.66&t=z1KGygPpr3bd9sKd-1&scaling=min-zoom&starting-point-node-id=1729%3A36833&show-proto-sidebar=1&mode=design

**Comment by SelinaBuff** [comment]
**You can find the Design on Figma. Go on the left menu on "🧩 Components" and then to the section "Popup (Password)":**

![Image](https://github.com/inovex/scrumlr.io/assets/116653219/fe66f6b9-bc94-4059-b8bc-4be234041ebd)
