### ISSUE TITLE
Consistent tooltip set

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#3106]
**User Stories:**

> 1. As a user, I expect the tooltips to consistently maintain the same style. This requires a reevaluation of the library. This ensures a cohesive design and a user-friendly language. It enhances recognizability and forms a unified and harmonious interface.
> 
> 2. As a user, I anticipate that the buttons will be tailored for both the dark and light modes to provide a seamless user experience in either setting.

**You can find the Design on Figma. Go on the left menu on "🎨 Style Guide" and then to the section "tooltip".**

![Image](https://github.com/inovex/scrumlr.io/assets/116653219/f8a07b02-e472-4994-a06c-a9b8c8f238bf)

**Comment by Kraft16** [comment]
Tooltip set:
https://www.figma.com/proto/8m2V6OJTImuOdQoxruWurP/Scrumlr?page-id=1725%3A29977&type=design&node-id=4051-31358&viewport=-10045%2C2660%2C0.7&t=2wm9hLm64bOeZXot-1&scaling=min-zoom&starting-point-node-id=1729%3A36833&show-proto-sidebar=1&mode=design
