### ISSUE TITLE
Write an article about scrumlr.io on inovex.de

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#3208]
Write an article about scrumlr.io, comparble to the [landing page of inoCube](https://www.inovex.de/de/leistungen/internet-of-things/projekt-inocube/), on inovex.de.

The arcticle can e.g. highlight the USPs of scrumlr.io as well as our great team.

**Comment by SelinaBuff** [comment]
as soon the
- Landingpage
- Emotions on notes
- Reactions

are done!
