### ISSUE TITLE
Scrumlr Brownbag presentation 6.9

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#3269]
**Scrumlr presentation on Wednesday **8/30/2023 12:15-12:40 pm** (Brownbag):**
_Presentation of project in 15 minutes: 12.15-12.30 p.m.
Questions and answers: 12.30-12.40 p.m._

This presentation should be prepared and given by the students themselves. Fortunately, there is already a presentation from the last Meetup that can be used.
It would be desirable if the following slides are added:

**Following focus of the presentation:**
- our general vision + goal of the whole project
- what has been achieved so far + goal for the next 4 months

**What can be presented:**
- Progress of the landing page (current ACTUAL state)
- Implementation of the Emotions on notes & possibly Reactions on board
- possibly Analytics

_Of course i can help with the visuals and we can go through the presentation together._

**Comment by brandstetterm** [comment]
Thank you for your really great presentation <3
