### ISSUE TITLE
Language Dropdown Broken

### ISSUE THREAD

**Issue by Resaki1** [inovex/scrumlr.io#3478]
### The problem

When clicking on the Language Dropdown inside the appearance settings, the dropdown is not visible. You have to scroll first to get to the dropdown.
This could probably be fixed by wrapping the dropdown in [react-doms `createPortal`](https://react.dev/reference/react-dom/createPortal#createportal)

### Browser

Firefox, Safari, and Arc (Chromium) for MacOS

### Steps to reproduce the behavior

- open appearance settings
- click on language dropdown

### Screenshots

https://github.com/inovex/scrumlr.io/assets/35272402/6b3b94c7-6978-4244-80e3-f7010bf38cc1

**Comment by blxckOxymoron** [comment]
what is your opinion on using a builtin `<select>` element? 
this would handle overflow and accessibility for us
the drawback is that you can't really style the options but you can of course style the button

**Comment by blxckOxymoron** [comment]
but I also found a way to get it back to work as it was before
I thought I had checked this but apparently I forgot to add the full height back in when adding the scrollbar
