### ISSUE TITLE
Note Reactions: StackView overlap

### ISSUE THREAD

**Issue by Schwehn42** [inovex/scrumlr.io#3499]
On smaller screens (approx. `320-350px`) in stack view, clicking on the "add reaction"-button – which opens the `NoteReactionBar` – will push off the `NoteDialogNoteOptions` component, as they're in the same grid row.

https://github.com/inovex/scrumlr.io/assets/7889564/3d2465c2-c604-402a-9dcd-d425c406a12c

**Comment by SelinaBuff** [comment]
We won't do the changes – it's just a problem for really old phones.
