### ISSUE TITLE
Add option to lock board

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#3538]
### Discussed in https://github.com/inovex/scrumlr.io/discussions/3030

<div type='discussions-op-text'>

<sup>Originally posted by **brandstetterm** May 30, 2023</sup>
I think it could be cool if a moderator could "lock" a board so that no more notes can be added / notes can't be edited anymore. </div>

**User Stories:**

> 1. As a moderator, I want the ability to lock a board so that no more notes can be added, in order to prevent further contributions and maintain the current state of the board.

> 2. As a moderator, I expect a simple and intuitive interface to lock and unlock the screen. (I can imagine this being included as an icon (lock) on the right side of the moderator menu.)

> 3. As a user, I want to receive visual feedback when the screen is locked. It should be clear that no further changes can be made.

**You can find the Design on Figma. Go on the left menu on "🧩  Components" and then to the section "Lock board":**

**Comment by SelinaBuff** [comment]
Design is done ✅

**Comment by brandstetterm** [comment]
Backend has been implemented by #3745
