### ISSUE TITLE
<button> cannot appear as a descendant of <button>

### ISSUE THREAD

**Issue by blxckOxymoron** [inovex/scrumlr.io#3567]
### The problem

when checking the dev tools, you see the following warning:

> [!WARNING]  
> Warning: validateDOMNesting(...): \<button> cannot appear as a descendant of \<button>.

The notes in the columns are using a `button` element for their outermost element. The reaction add button inside of the note is the second `button` mentioned in the warning.

### Browser

Firefox, Chrome

### Steps to reproduce the behavior

- start server and frontend
- add a note
- check the console

**Comment by Schwehn42** [comment]
So I get that React would show this message, but semantically, it makes sense imo for the Notes to be `button`s, and some elements inside it as well. Even if it's not best practice 👀

**Comment by blxckOxymoron** [comment]
well you could also argue, that it's primary function isn't a button to be clicked but a regular container to display the note's tetxt. 
it should also be noted that this isn't a react thing but something specified in the [HTML standard](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element) (also see [this SO question](https://stackoverflow.com/questions/39386497/can-i-nest-button-inside-another-button))

**Comment by Schwehn42** [comment]
Ok I agree, then we should change that :)
