### ISSUE TITLE
"Rejection" page

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#3619]
**User Stories:**

**For Design:**

> 1. As a user, I expect a consistent design. Accordingly, please review:
>    - Colors
>    - Font size
>    - Spacing
>    - Buttons

**For Development:**

> 1. As a user, I expect a clearly communicated message on the "Error page."
> 2. As a user, I expect a direct way to return to the homepage.

**You can find the Design on Figma. Go on the left menu on "🚫 Error Page" and then to the section "Rejection Page":**

_Currently it looks like this:_

![Image](https://github.com/inovex/scrumlr.io/assets/116653219/79d1138c-0c66-42a9-89fa-d003c4873a86)

_But we want this:_

![Image](https://github.com/inovex/scrumlr.io/assets/116653219/6aa726f6-cca7-4438-b46f-d0245d984a27)

**Comment by Schwehn42** [comment]
the same design is already used for the 404 page https://github.com/inovex/scrumlr.io/pull/2899, so using a prop to change the text should probably be sufficient

**Comment by SelinaBuff** [comment]
The Maindesign of the "Error-page" has changed a little bit. Had to improve some view details because of our design library (color check, button check, font size). But the design is done now!
