### ISSUE TITLE
The buttons within the voting pill should be swapped

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#3727]
Normally there are buttons to cancel on the left-hand side and buttons to "Save" on the right-hand side. For this reason, the order of the buttons within the voting pill should be changed.

![Image](https://github.com/inovex/scrumlr.io/assets/36969812/b979cc1d-def4-4e5a-82b2-cb879ffa16d0)

**Comment by varungujarathi9** [comment]
Hey @brandstetterm, I would like to work on this, I have experience with React

**Comment by brandstetterm** [comment]
Hey @varungujarathi9, with pleasure! I look forward to your contribution

**Comment by varungujarathi9** [comment]
Hey @brandstetterm I was able to run the project on local over the weekend. 

Currently, the div with conclude and cancel buttons opens on the right when hovered, but to make changes for the issue, should we make it open on the left when hovered?

**Comment by brandstetterm** [comment]
Hey @varungujarathi9, please simply swap the two buttons with each other. Your screenshot looks fine. Please submit a pull request 😄

**Comment by varungujarathi9** [comment]
Great, raised a PR

**Comment by brandstetterm** [comment]
Thank you very much for your contribution @varungujarathi9 !
