### ISSUE TITLE
Google Oauth 2.0 not supported

### ISSUE THREAD

**Issue by ImDevinC** [inovex/scrumlr.io#3764]
### The problem

When configuring an app for Google authentication, we get the following error

> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

### Browser

Chrome

### Steps to reproduce the behavior

Configure google credentials with an app and login using a Google workspace account

### Screenshots

<img width="444" alt="Screenshot 2024-01-17 at 3 10 41 PM" src="https://github.com/inovex/scrumlr.io/assets/3997333/114e172a-7499-4049-9155-267aed539857">

**Comment by Lennart01** [comment]
Hey sorry for the late reply. Would you mind expanding the error (`error details`).
I assume you didn't configure the redirect URL correctly. We have Oauth2 Running in Production without issues.
