### ISSUE TITLE
Dependabot open-pull-requests-limit doesn't seem to work

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#378]
https://github.com/inovex/scrumlr.io/blob/ea634dc1f7b82b527196bddb99bdcf800dc8938a/.github/dependabot.yml#L10

Doesn't seem to work because yesterday (28th April) I merged 14 open Dependabot pull requests

**Comment by bitionaire** [comment]
It works, because these limits exist both on the frontend and server - so in sum 20 :)
