### ISSUE TITLE
The visual indication for image links should align with the plus icon within the note input

### ISSUE THREAD

**Issue by brandstetterm** [inovex/scrumlr.io#3847]
As a user, I want the visual indication for image links (first icon) to align with the plus icon (second icon) within the note inputs at the top of columns. Both icons should be aligned at the top. 

![Image](https://github.com/inovex/scrumlr.io/assets/36969812/82daa7b0-1f06-4dfe-b7ca-ac71bbec76e8)

**Comment by blxckOxymoron** [comment]
There are also sparkles on the background of the image indicator, should they be...
1. kept where they are
2. removed
3. moved to the bottom half

**Comment by CronJorian** [comment]
I'd say either remove or scale to the image icon.
I currently implemented it scaled to the icon, if something different is desired just @ me.

Another approach could be to move the image icon to the top right (or whatever) corner.
There it would not take so much space on smaller space and be more prominent for users to see.

![image](https://github.com/inovex/scrumlr.io/assets/44020029/68e38635-5a36-4a42-a9b9-b37285847eee)
vs.
![image](https://github.com/inovex/scrumlr.io/assets/44020029/c20c4d07-0d00-4505-9445-3c7c961bdd26)
