### ISSUE TITLE
Add uniform design for ReactionChips with 10+ reactions

### ISSUE THREAD

**Issue by Schwehn42** [inovex/scrumlr.io#3895]
ReactionsChips with 10+ reactions don't respect the paddings.  
(Also, the Tooltip looks silly because it's all in one line.)

![Image](https://github.com/inovex/scrumlr.io/assets/7889564/e951c186-9b9a-4940-b42d-b08874e75c20)

**Comment by SelinaBuff** [comment]
8px Padding left & right

**Comment by dipesh1903** [comment]
@SelinaBuff , can I take up this issue to adjust the padding. 

And for the tooltips, we can show the initial 2 to 3 person name followed by the count of remaining person. For example for 6 person reactions we can show something like  -> 
**person1 , person2, +4** .

**Comment by SelinaBuff** [comment]
@dipesh1903 that would be great! Thank you

**Comment by dipesh1903** [comment]
@SelinaBuff  , I'm unable to assign this ticket to myself, Can you help me here.
Thanks,

**Comment by Schwehn42** [comment]
done, see https://github.com/inovex/scrumlr.io/pull/4554 and https://github.com/inovex/scrumlr.io/releases/tag/v3.10.0
