### ISSUE TITLE
Website not available

### ISSUE THREAD

**Issue by ygoe** [inovex/scrumlr.io#3915]
### The problem

I was on your recent presentation and took some of the paper cards with me. When I enter the address written on them, I cannot access the page. This hasn't changed in the past 3 or 4 weeks.

### Browser

All

### Steps to reproduce the behavior

Open http://www.scrumlr.io

### Screenshots

`404 page not found`

### Additional context

Works without "www." so it's probably a small web server configuration issue. But it has a major impact and I'm wondering that nobody noticed that yet.

**Comment by Schwehn42** [comment]
Hello @ygoe, thanks for reaching out and the report – we are aware of the issue and will be deploying a fix as soon as we can :) you can also keep an eye on this ticket to follow the status and get notified when it's completed.

**Comment by Lennart01** [comment]
Fixed thanks for reporting this 😄
