### ISSUE TITLE
Add inline URLs to notes

### ISSUE THREAD

**Issue by Schwehn42** [inovex/scrumlr.io#3969]
When a note contains one or more URLs, they could be formatted as clickable links:

* link is clickable (open in new tab)
* formatted in a blue color, maybe underlined
* maybe truncate the link, so https://example.com/path/to/file?key=value#123 becomes just [https://example.com...](https://example.com) or something like that

**Comment by brandstetterm** [comment]
Hi, please use our [Discussions](https://github.com/inovex/scrumlr.io/discussions) for future ideas 🙂 Our issues should be kept clean

**Comment by Schwehn42** [comment]
sure thing. iirc I added the issue to the backlog which seems to also appear here – in any case, it would make sense removing the _Idea_ label if it shouldn't be used then?
