### ISSUE TITLE
Make QR code exportable as image

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#4170]
### Discussed in https://github.com/inovex/scrumlr.io/discussions/3870

<div type='discussions-op-text'>

<sup>Originally posted by **Resaki1** February 15, 2024</sup>
Currently, the QR code to share a session is rendered as an SVG. Right-clicking it does not give the option to save the QR code as an image (at least in Chromium). Of course you could make a screenshot, but rendering it as an image would make it easier imo</div>

**Comment by Schwehn42** [comment]
using `canvas` instead of ´svg´ and upscaling it does the trick
