### ISSUE TITLE
inline emoji menu is shown behind notes

### ISSUE THREAD

**Issue by BenedictHomuth** [inovex/scrumlr.io#4362]
### The problem

When there are notes on a board, and I want to type in an emoji for a new note, the menu is displayed behind the already present notes.

Similar issue when I want to edit a note, that was already present

### Browser

Chrome

### Screenshots

On board:
![image](https://github.com/user-attachments/assets/91c56dbe-0fe4-402d-8e44-98aad0265d90)

In Note view:
![image](https://github.com/user-attachments/assets/d4a34fd7-57e3-4915-9c9e-b5c6f9e2ab23)

**Comment by liza-kl** [comment]
Fix proposed in #4391
