### ISSUE TITLE
Feedback Slack integration is not working

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#4420]
### The problem

**Feedback Slack integration is not working**

**Description:**
Our Feedback Slack integration is no longer functioning. We are not receiving notifications about incoming feedback in the Slack channel. Please investigate and fix the issue so that feedback messages are sent to Slack as expected.

**Acceptance Criteria:**
- Feedback messages are properly delivered to the designated Slack channel again.

### Browser

Chrome

**Comment by Schwehn42** [comment]
This works again, thanks @brandstetterm

**Comment by brandstetterm** [comment]
Also thanks to @Lennart01
