### ISSUE TITLE
Automatically reset "Mark me as done"

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#4427]
### Automatically Reset "Mark me as done" for Multiple Actions

**Description:** The "Mark me as done" status for participants should automatically reset as soon as an action occurs. Currently, the status is only reset when a single action is completed (e.g., timer ends). However, if a new action, such as voting, starts immediately after, the status is not reset.

This should be adjusted so that the status is reset automatically for consecutive actions as well. As a result of this change, the "Reset Toast" will likely no longer be necessary and can be removed.

**Acceptance Criteria:**
- The "Mark me as done" status is automatically reset for every action, including consecutive ones.
- The "Reset Toast" is no longer needed and should be removed.

**Browser:** Chrome

**Comment by Schwehn42** [comment]
done with https://github.com/inovex/scrumlr.io/pull/4383 I think
