### ISSUE TITLE
Firefox Tabbing

### ISSUE THREAD

**Issue by Schwehn42** [inovex/scrumlr.io#4500]
### The problem

When using the keyboard, tabulator doesn't work as expected when using the columns menu or the note reactions menu.

### Browser

Firefox

### Steps to reproduce the behavior

Open the columns menu or note reactions menu using tabulator. Both menus cannot be accessed properly, unlike Chrome, for example.

**Comment by Aejkatappaja** [comment]
Hello,

#4562
