### ISSUE TITLE
Adjust Padding for "+-Button" in Note Input Field

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#4551]
# Adjust Padding for "+-Button" in Note Input Field 

**Description:** 
In the input field used for writing a note, there is too much padding to the right of the "+-button" compared to the border of the input field. Please adjust it so that the right-side padding is the same as the left-side padding.

**Acceptance Criteria:**
- The padding on the right side of the "+-button" matches the padding on the left side
- The change is correctly displayed in all major browsers

![Image](https://github.com/user-attachments/assets/f40ec6d1-2869-44b9-b1a3-a762867e3a7a)
![Image](https://github.com/user-attachments/assets/727b2a25-d9ce-42f2-a830-0f7484e54c1c)

**Comment by dipesh1903** [comment]
@SelinaBuff  , can you please assign this issue to me.

**Comment by SelinaBuff** [comment]
@dipesh1903 after it took so long to assign the ticket to you (I'm very sorry!) – you're now assigned. I hope you remain interested in fixing the problem :)

**Comment by dipesh1903** [comment]
@SelinaBuff  I've raised a PR for this ticket. Can someone look into this 

PR: https://github.com/inovex/scrumlr.io/pull/4695
