### ISSUE TITLE
Show tooltip only for truncated headings

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#4553]
### Show tooltip only for truncated headings

**Description:** Currently, the tooltip is displayed regardless of the length of the heading. The tooltip should only appear when a heading is truncated due to its length and is not fully readable. Headings that are short enough and can be fully displayed do not need a tooltip, as the content is already visible at a glance.

**Requirements:** 
- The tooltip should be shown only when the heading text is longer than the available space and is thus truncated
- No tooltip should be displayed for fully visible headings
- Ensure that this behavior is consistent across different browsers and devices

![Image](https://github.com/user-attachments/assets/cfced276-84ba-4aec-bc94-1245557103ad)

**Comment by Aejkatappaja** [comment]
Hello, 

[PR here](https://github.com/inovex/scrumlr.io/pull/4557)
