### ISSUE TITLE
votings/votes inconsistencies on reload

### ISSUE THREAD

**Issue by Schwehn42** [inovex/scrumlr.io#4585]
### The problem

votes by other participants aren't shown upon reloading. Apparently, only your own votes are sent in the `INIT` event.

In the steps to reproduce, one vote was cast for each participant. The resulting data for the `INIT` event is the following:

**User 1**
```json
"votings": [
      {
        "id": "945f4570-34d0-4dc2-b8bd-9cc61098e944",
        "voteLimit": 1,
        "allowMultipleVotes": false,
        "showVotesOfOthers": false,
        "status": "CLOSED",
        "votes": {
          "total": 1,
          "votesPerNote": {
            "d48b08a0-c645-49f4-8aad-f774cf5dbfc4": {
              "total": 1
            }
          }
        }
      }
    ],
"votes": [
  {
    "voting": "945f4570-34d0-4dc2-b8bd-9cc61098e944",
    "note": "d48b08a0-c645-49f4-8aad-f774cf5dbfc4"
  }
]
```

**User 2**
```json
"votings": [
      {
        "id": "945f4570-34d0-4dc2-b8bd-9cc61098e944",
        "voteLimit": 1,
        "allowMultipleVotes": false,
        "showVotesOfOthers": false,
        "status": "CLOSED",
        "votes": {
          "total": 1,
          "votesPerNote": {
            "70c1fc59-db1b-45e9-8164-51888c7f0040": {
              "total": 1
            }
          }
        }
      }
    ],
"votes": [
  {
    "voting": "945f4570-34d0-4dc2-b8bd-9cc61098e944",
    "note": "70c1fc59-db1b-45e9-8164-51888c7f0040"
  }
]
```

As one can see, both `votings` and `votes` do not include votes by others. This likely is a mistake in the backend.

### Browser

Firefox

### Steps to reproduce the behavior

1. create a new board, join with two different participants
2. create a note
3. create a voting
4. vote on the note
5. close voting
6. (here, all votes should be correctly shown)
7. reload page
8. only your own votes should be shown here

### Screenshots

The screenshots are what the board looks like for each user **after reloading**.
<img width="939" alt="voting-user-1" src="https://github.com/user-attachments/assets/cfb6ce16-4dba-41f5-952f-60596202f50a">
<img width="939" alt="voting-user-2" src="https://github.com/user-attachments/assets/45714150-da8d-405a-adfc-77b56840a59a">

**Comment by Nilegfx** [comment]
voting is super important feature. is there any plans to solve this bug soon?

**Comment by Schwehn42** [comment]
@Nilegfx Yes, we're currently working on it :)

**Comment by Schwehn42** [comment]
fixed in https://github.com/inovex/scrumlr.io/releases/tag/v3.10.0
