### ISSUE TITLE
Service Disruption (IPv6) of scrumlr.io

### ISSUE THREAD

**Issue by frederictobiasc** [inovex/scrumlr.io#4678]
### The problem

Currently, the AAAA DNS records of scrumlr.io point to a server (2a0a:9901:a000:0:f816:3eff:fe45:88)  that doesn't respond.

This means that the websites cannot be reached at all from some networks. For instance, networks with NAT64 enabled.

To rectify this, please ensure that the IPv6 address of the server matches the DNS entries (2a0a:9901:a000:0:f816:3eff:fe45:88).

If there is no other way to restore the IPv6 connection of the web server, please remove the AAAA DNS entries so that the configuration is not broken any more.

Thank you

### Browser

Firefox

### Steps to reproduce the behavior

Access scrumlr.io via the IPv6 address provided by DNS.

### Screenshots

![grafik](https://github.com/user-attachments/assets/5570f1c0-f281-4fd4-90da-85e1c51a5e6b)

**Comment by Lennart01** [comment]
Hey, sorry, we initially planned to support IPv6 (hence the record ^^). 
Unfortunately, our cluster is currently single stack. 
We have removed the record.
