### ISSUE TITLE
Minor localization Issue: "Ohne Passwort fortfahren" appears in English locale when importing password-protected board

### ISSUE THREAD

**Issue by cerux1867** [inovex/scrumlr.io#4680]
### The problem

I found a minor translation issue (fitting for someone who works at a localisation tech company 😁) importing a board using the new `3.10.0` feature and the board is password protected, the button to skip password setup and leave it public has  German text "Ohne Passwort fortfahren" but the locale is set to English. 

### Browser

Chrome

### Steps to reproduce the behavior

1. Navigate to home page - in my case self hosted on `scrumlrio.<company URL>.com`
2. Select English locale
3. Click on "Start Now"
4. Click on "Import JSON"
5. Select a exported board that has password protection
6. The popup will have a button for skipping that says "Ohne Passwort fortfahren"

### Screenshots

![Screenshot 2024-12-10 at 14 54 25](https://github.com/user-attachments/assets/1224182e-6da7-4d74-9f08-69524195f2e8)

**Comment by Schwehn42** [comment]
thanks for the bug report @cerux1867, should be fixed with the next patch :)
