### ISSUE TITLE
Login Provider Azure AD and Apple oauth removed in version v3.8.0

### ISSUE THREAD

**Issue by AnBenni** [inovex/scrumlr.io#4708]
### The problem

With PR https://github.com/inovex/scrumlr.io/pull/4223 the possibility for login with Azure AD or Apple OAuth were removed.
See commit https://github.com/inovex/scrumlr.io/pull/4223/commits/963757b8941fd7275add8b522a8b96ab802d7627
file src/components/LoginProviders/LoginProviders.tsx.

We use Azure AD login only and thus aren't able to update scrumlr anymore.

### Browser

all browsers

### Steps to reproduce the behavior

Configure Azure AD login by env variables:
  - SCRUMLR_AUTH_AZURE_AD_TENANT_ID
  - SCRUMLR_AUTH_AZURE_AD_CLIENT_ID
  - SCRUMLR_AUTH_AZURE_AD_CLIENT_SECRET
  - SCRUMLR_AUTH_CALLBACK_HOST

Bowse to /login page. 
=> No "Sign in with Azure AD" button anymore.

### Screenshots

![v3 7 1](https://github.com/user-attachments/assets/518e0e6c-bcf8-4aff-a28f-fc8ee293df48)
![v3 8 0](https://github.com/user-attachments/assets/2e1efec0-5f8a-489f-aae8-d028a220c8f6)

**Comment by Schwehn42** [comment]
Hi @AnBenni, thanks for pointing this out, you're totally right! I'll try to get this fixed soon so you can upgrade.

**Comment by Schwehn42** [comment]
@AnBenni this should be fixed and released in https://github.com/inovex/scrumlr.io/releases/tag/v3.10.1, let me know if it works for you :)

**Comment by AnBenni** [comment]
Hi @Schwehn42.
Great, it works again. Thank you so much, I'm very happy!

 I had to add the new env variable SESSION_SECRET to the scrumlr server in my k8s environment, otherwise I got an error: "you may not start the application without a session secret if an authentication provider is configured". This was not necessary before.
 I guess it is some improvement.
