### ISSUE TITLE
Automatic scaled font size

### ISSUE THREAD

**Issue by jannsk** [inovex/scrumlr.io#54]
It would be cool if you could scale the font size while focusing a card.

Problem:
I cannot see the whole text of my focused card. No way to scroll etc.
![image](https://user-images.githubusercontent.com/11212381/39692384-fe5a5238-51e0-11e8-8747-504d6ceeb480.png)

Expected output: 
I can see the whole text of a card or have any other way to see the text.

**Comment by bitionaire** [comment]
Hey @jannsk, sorry but we won't fix this in the current version as we are progressing towards the release of our refactoring, which we call "V2". :)
