### ISSUE TITLE
Bucket Estimation mode

### ISSUE THREAD

**Issue by wlbr** [inovex/scrumlr.io#76]
The Admin can define multiple swimlanes with a header.
New cards will be added only to the first column (=backlog).

During the session the users drag&drop the cards between the swimlanes.

Optional: Cards have a counter that increases everytime they are rearranged. 
Optional: Once cards are moved outside the backlog they can be rearranged only once. Another move will automatically put them into a special "conflict" column.

**Comment by bitionaire** [comment]
Hey @wlbr, we considered this feature request for our "V2" which is currently in development and we hope that we'll be able to release it this year
