### ISSUE TITLE
As a moderator i would like to see the author of the card in presentation mode

### ISSUE THREAD

**Issue by katringietemann** [inovex/scrumlr.io#761]
In presentation mode, it would be super helpful if I could see who wrote the card. So I can refer to the author, ask him to add something without having to leave the presentation mode every time to see who wrote the card.

**Comment by bitionaire** [comment]
Hi @katringietemann, good catch and thank you for your feedback! 
Seems obvious yet I can't remember someone mentioning this issue :) 

You can map the author of the focused note by looking up the note which has an increased drop shadow on the column.

![scrumlr io_](https://user-images.githubusercontent.com/1539948/135149493-606aa1e2-7824-4aee-b443-8fb2d484a1c4.png)

I understand that it's not the best option but we (unintentionally or maybe on purpose?) fixed this issue in the new version & design we're currently working on. Hope this workaround will help you until we'll release scrumlr next generation :)
