### ISSUE TITLE
Empty if statement

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#849]
Hey @Dominik-Weinzierl, can you have a look into
https://github.com/inovex/scrumlr.io/blob/ca823f5292fd317e6f7b72d3c98cda964de9defe/src/store/reducer/board.ts#L40

I don't get whether something is missing or this can be deleted.

**Comment by Dominik-Weinzierl** [comment]
Yes, you are right. Since we extracted this logic into a new function (and action), this isn't needed anymore. Good catch. Thank you :D
