### ISSUE TITLE
Attemts to join via passphare should be rate limited

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#857]
Attempts to join via a passphrase should be rate limited and denied after a limited number of retries (e.g. 60 sec. pause after 5 retries) 

See #856

**Comment by brandstetterm** [comment]
https://github.com/go-chi/httprate can be used for this. Maybe you could use a specific rate limit by IP and by board id, so a user can only try to join (reloads included) a specific board 5 times every 2 minutes

**Comment by bitionaire** [comment]
Already implemented
