### ISSUE TITLE
Refactor SVG assets

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#938]
I think it would be best if we refactor the SVG assets manually so that

... all `fill` and `stroke` colors will be defined by `="currentColor"` for assets which use only one color. We can then simple set `color: #<somehex>` instead of using the `.<class> * { fill: ...}` selector
... all assets should have no padding and the padding should be defined by the wrapping HTML element. This will make them more reusable
... the assets can be manually minified, e.g. if `fill="none"` is set `file-rule="evenodd"` is not necessary

**Comment by Dominik-Weinzierl** [comment]
Regarding the padding: I think this is not easily done on a nice way (sure we could move the viewBox), so i think we should create new svgs without padding in the future and keep the padding as it is right now 🤔 What do you think?

**Comment by jdolinga** [comment]
I minified the svgs, checked currentColor and viewBoxes. If a viewBox had parameters for x or y values, I refactored the svg.

I found a few icons, that aren't used in the project: icon-coloumn, icon-addimage, icon-addsticker, icon-confetti, icon-export-pdf. Can I delete them?
