### ISSUE TITLE
Online detection of users not working

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#966]
... users are always marked online on my local setup. Seems to be a bug there

**Comment by Dominik-Weinzierl** [comment]
Mhm, works as expected on my local setup 🤔

**Comment by bitionaire** [comment]
Yeah, I got the issue. If you start the server dockerized, so that server & livequery server are separated the cloud functions and especially the `onLiveQueryEvent()` function within `cloud/board.ts` won't be initialized and therefore will never trigger.
